import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
import Header from "../../component/Header/page";
import { RightMenuDesktop } from "../../component/navbarDesktop/page";
import { NavColorProvider } from "../context/NavColorContext";
import Footer from "@/component/Footer/page";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  type Props = {
    navColor: string;
  };

  return (
    <>
      <div className=" flex flex-col bg-[#f0f2f5]">
        <NavColorProvider>
            <div className="flex">
              <div >
                <RightMenuDesktop />
              </div>
              <div className="w-full">
                <Header />
                <main className=" flex-1 p-6">
                  {children}
                </main>
                <Footer />
              </div>
            </div>
        </NavColorProvider>
      </div>
    </>
  );
}
