import type { Metadata } from "next";
import Header from "../../component/Header/page";
import { RightMenuDesktop } from "../../component/navbarDesktop/page";
import { NavColorProvider } from "../context/NavColorContext";
import Footer from "@/component/Footer/page";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  type Props = {
    navColor: string;
  };

  return (
    <>
      <div className=" flex flex-col ">
        <NavColorProvider>
            <div className="flex">
              <div >
                <RightMenuDesktop />
              </div>
              <div className="w-full">
                <Header />
                <main className=" flex-1 p-6">
                  {children}
                </main>
                <Footer />
              </div>
            </div>
        </NavColorProvider>
      </div>
    </>
  );
}
